version: '2'
services:
  dev:
    image: docker.lzzhao.app:4567/lzzhao/web-dev-env/master
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: bash
    stdin_open: true
    tty: true
    environment: 
    - USER=ubuntu
    - PASSWORD=tongji
    ports:
      - 1234:1234
      - 1235:1235
      - 42222:22
